name: Lint with MyPy

on: [push, pull_request]

jobs:
  mypy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        env:
          PIP_EXTRA_INDEX_URL: https://aa:${{ secrets.PYPI_PASSWORD }}@pypi.autoactuary.com/simple
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r mypy-requirements.txt

      - name: Run MyPy
        run: |
          mypy .
